apiVersion: v1
kind: Secret
metadata:
  name: media-discovery-secrets
type: Opaque
stringData:
  tmdb-token: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzYTg1N2I5NzQ1YTFkMTQ1OGZjNTM4NGRhYTlmZGZlYiIsIm5iZiI6MTc2NTA2Nzk0OS41OTEsInN1YiI6IjY5MzRjY2FkN2Q2MDI1Mzg4MDQ4ZWEwMSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.cFPXKYUBIdG9k8-CX-XjW_F_lQzPJ63mz4fiPDFZ1_s"
